/*
 * MaestroHostService
 *
 * This is the Host API for Maestro System
 *
 * OpenAPI spec version: 1.0.0
 * Contact: febo74@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Data of the complete structure of the scene.
    /// </summary>
    [DataContract]
    public partial class Scene : IEquatable<Scene>
    { 
        /// <summary>
        /// Gets or Sets SceneMetadata
        /// </summary>
        [DataMember(Name="sceneMetadata")]
        public SceneMetadata SceneMetadata { get; set; }

        /// <summary>
        /// Gets or Sets Scenarios
        /// </summary>
        [DataMember(Name="scenarios")]
        public Scenarios Scenarios { get; set; }

        /// <summary>
        /// Gets or Sets LearningPaths
        /// </summary>
        [DataMember(Name="learningPaths")]
        public LearningPaths LearningPaths { get; set; }

        /// <summary>
        /// Gets or Sets Targets
        /// </summary>
        [DataMember(Name="targets")]
        public Targets Targets { get; set; }

        /// <summary>
        /// Gets or Sets Contents
        /// </summary>
        [DataMember(Name="contents")]
        public Contents Contents { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Scene {\n");
            sb.Append("  SceneMetadata: ").Append(SceneMetadata).Append("\n");
            sb.Append("  Scenarios: ").Append(Scenarios).Append("\n");
            sb.Append("  LearningPaths: ").Append(LearningPaths).Append("\n");
            sb.Append("  Targets: ").Append(Targets).Append("\n");
            sb.Append("  Contents: ").Append(Contents).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Scene)obj);
        }

        /// <summary>
        /// Returns true if Scene instances are equal
        /// </summary>
        /// <param name="other">Instance of Scene to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Scene other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    SceneMetadata == other.SceneMetadata ||
                    SceneMetadata != null &&
                    SceneMetadata.Equals(other.SceneMetadata)
                ) && 
                (
                    Scenarios == other.Scenarios ||
                    Scenarios != null &&
                    Scenarios.Equals(other.Scenarios)
                ) && 
                (
                    LearningPaths == other.LearningPaths ||
                    LearningPaths != null &&
                    LearningPaths.Equals(other.LearningPaths)
                ) && 
                (
                    Targets == other.Targets ||
                    Targets != null &&
                    Targets.Equals(other.Targets)
                ) && 
                (
                    Contents == other.Contents ||
                    Contents != null &&
                    Contents.Equals(other.Contents)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (SceneMetadata != null)
                    hashCode = hashCode * 59 + SceneMetadata.GetHashCode();
                    if (Scenarios != null)
                    hashCode = hashCode * 59 + Scenarios.GetHashCode();
                    if (LearningPaths != null)
                    hashCode = hashCode * 59 + LearningPaths.GetHashCode();
                    if (Targets != null)
                    hashCode = hashCode * 59 + Targets.GetHashCode();
                    if (Contents != null)
                    hashCode = hashCode * 59 + Contents.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Scene left, Scene right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Scene left, Scene right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
