/*
 * MaestroHostService
 *
 * This is the Host API for Maestro System
 *
 * OpenAPI spec version: 1.0.0
 * Contact: febo74@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{         /// <summary>
        /// The type of the file content.
        /// </summary>
        /// <value>The type of the file content.</value>
        public enum ContentType
        { 
            /// <summary>
            /// Enum TextEnum for text
            /// </summary>
            [EnumMember(Value = text)]
            TextEnum = 1,
            
            /// <summary>
            /// Enum ImageEnum for image
            /// </summary>
            [EnumMember(Value = image)]
            ImageEnum = 2,
            
            /// <summary>
            /// Enum VideoEnum for video
            /// </summary>
            [EnumMember(Value = video)]
            VideoEnum = 3,
            
            /// <summary>
            /// Enum ModelEnum for model
            /// </summary>
            [EnumMember(Value = model)]
            ModelEnum = 4
        }
}
