/*
 * MaestroHostService
 *
 * This is the Host API for Maestro System
 *
 * OpenAPI spec version: 1.0.0
 * Contact: febo74@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{         /// <summary>
        /// The user type: Admin or member.
        /// </summary>
        /// <value>The user type: Admin or member.</value>
        public enum UserType
        { 
            /// <summary>
            /// Enum AdminEnum for admin
            /// </summary>
            [EnumMember(Value = admin)]
            AdminEnum = 1,
            
            /// <summary>
            /// Enum MemberEnum for member
            /// </summary>
            [EnumMember(Value = member)]
            MemberEnum = 2
        }
}
